### ISSUE TITLE
crack_rho

### ISSUE THREAD

**Issue by Sonya21** [qubd/mini_ecdsa#1]
Hi. How to run crack_rho
for the public key bitcoin. Where do I enter the data, can I use an example?

**Comment by qubd** [comment]
Oh. I didn't update the README after adding an extra argument to crack_rho, so I've done that now.

The arguments you need to provide are, firstly, an elliptic curve C, base point P, it's order n, and the public key Q. In your case, C = CurveOverFp.secp256k1(), P = Point.secp256k1(), and n is given in the README.

Finally, the value for the last argument, bits, can be used to tune the algorithm. I'm honestly not sure about how to best choose it. In Menezes, Hankerson, and Vanstone's Guide to Elliptic Curve Cryptography, they suggest that 4 and 5 are typical values (corresponding to 16 and 32 branches, in their terminology), though they give no indication why and provide no references (!?).

Note that bitcoin addresses are not public keys. They've been run through cryptographic hash functions, so there's no effective way to recover the public key, given **only** the associated bitcoin address. When coins are spent, the public key for the address they come from has to be revealed so that ECDSA can be used to check the validity of the transaction, but secp256k1 has a lot of points on it. The parameters have been chosen so that well known methods like Pollard's rho are much too slow to ever crack a correctly generated public key in practice.

**Comment by Sonya21** [comment]
>>> C.contains(P)
True
>>> C.contains(Q)
True
>>> crack_rho(C, P, n, Q, 4)

work
secp256k1
how to know the speed selection?where the selection starts?you can specify the beginning of the selection?you can parallelize and add PyCUDA?run Brutus for many public keys? Can work in a team ,I will be able to rent 1600 cores xeon e5.What are the odds?
