### ISSUE TITLE
How to set data and start crack_rho on Windows 7 (86x)?

### ISSUE THREAD

**Issue by amiwrcd** [qubd/mini_ecdsa#3]
Hello! I can not figure out the data (C, P, n, Q, 4)? I'm a newbie. How to set data and start crack_rho on Windows 7 (86x)? Thanks in advance for the answer

**Comment by qubd** [comment]
These variables are defined in the code box above the three cracking
methods in the readme, which reads as follows:

>>> C = CurveOverFp(0, 1, 7, 729787)
y^2 = x^3 + x + 7 over F_729787
>>> P = Point(1,3)
>>> n = C.order(P)
>>> (d, Q) = generate_keypair(C, P, n)
Priv key: d = 692847
Publ key: Q = (257099,102580)


In general, we have:

C: an elliptic curve
P: the base point on that curve
n: the order of the base point P
Q: another point on the curve such that Q = dP for some integer d (the
point Q is used as a public key with private key d)

Best,

Brendan

**Comment by amiwrcd** [comment]
As I understand it, if you use secp256k1, then the parameters:
P = Point(55066263022277343669578718895168534326250603453777594175500187360389116729240, 32670510020758816978083085130507043184471273380659243275938904335757337482424)
n = 115792089237316195423570985008687907852837564279074904382605163141518161494337
How to run all this on a PC with Windows 7?

**Comment by qubd** [comment]
I'm not going to explain to you how to install and run python. I'm sure you
can find lots of documentation on that.

Brendan

**Comment by amiwrcd** [comment]
I have Python installed, but how to enter data is not entirely clear?

Q = (021212393681475256946188857575664116764765889223328029212753885355123098405756,105973048369535734387521722323100020016701048012120686658235512163653375216393)
d = 77046866139867225667655181581886052514593693348265198158669507072467388698768
P = Point(55066263022277343669578718895168534326250603453777594175500187360389116729240, 32670510020758816978083085130507043184471273380659243275938904335757337482424)
n = 115792089237316195423570985008687907852837564279074904382605163141518161494337

**Comment by SatoshiNakamotoBitcoins** [comment]
@amiwrcd I would advise you to run a Virtual Box on your Win7 machine. Install a Linux distribution; Ubuntu, Kali Linux, Xubuntu etc...
After that you can run Python on your Linux distribution (out of the box this Python script will not run...first you have to make it a executable)

Take these steps first, come back to this thread and I will make sure that you can roll the dice...;-)

**Comment by SatoshiNakamotoBitcoins** [comment]
@amiwrcd But to be honest mate...don't waste your time...

Read this article:

https://andrea.corbellini.name/2015/06/08/elliptic-curve-cryptography-breaking-security-and-a-comparison-with-rsa/

And this phrase is important to now:

We said that baby-step giant-step can't be used in practice, because of the huge memory requirements. Pollard's rho, on the other hand, requires very few memory. So, how practical is it?

Certicom launched a challenge in 1998 to compute discrete logarithms on elliptic curves with bit lengths ranging from 109 to 359. As of today, only 109-bit long curves have been successfully broken. The latest successful attempt was made in 2004. Quoting Wikipedia:

    The prize was awarded on 8 April 2004 to a group of about 2600 people represented by Chris Monico. They also used a version of a parallelized Pollard rho method, taking 17 months of calendar time.

As we have already said, prime192v1 is one of the "smallest" elliptic curves. We also said that Pollard's rho has O(n√)
time complexity. If we used the same technique as Chris Monico (the same algorithm, on the same hardware, with the same number of machines), how much would it take to compute a logarithm on prime192v1?
17 months ×2192−−−√2109−−−√≈5⋅1013 months

This number is pretty self-explanatory and gives a clear idea of how hard it can be to break a discrete logarithm using such techniques.

**Comment by qubd** [comment]
That's a lot of trouble. Why not just install a Windows friendly all-in-one
python like Anaconda and load this package in the interpreter as I did in
the readme?

**Comment by amiwrcd** [comment]
Brendan, is it possible to run "crack_rho" to search for private keys from a list containing 10 000 000 public keys? I need to find at least one or two private keys out of 10 000 000 public keys.

**Comment by dem10** [comment]
Now the tool works on 1 thread. Is there an opportunity to make it multithreaded?

**Comment by qubd** [comment]
Yes. Feel free!

**Comment by dem10** [comment]
> Yes. Feel free!
Could you make your tool multithreaded? So probably my question will be correct.

**Comment by qubd** [comment]
No.
